services:
  mysql:
    image: mysql:8.0
    container_name: mysql_pipeline
    environment:
      - MYSQL_ROOT_PASSWORD=senha_secreta
      - MYSQL_DATABASE=restaurante_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis_pipeline
    ports:
      - "6379:6379"
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n_pipeline
    ports:
      - "5678:5678"
    environment:
      - N8N_ENFORCEMENT_AGREEMENT=true
      - GENERIC_TIMEZONE=America/Sao_Paulo
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
  n8n_data: